name: mcg76_Prax
version: 1.7.0
api: 1.6.0
main: Praxthisnovcht\CustomChat\CustomChat
author: Praxthisnovcht & Dax & Supra
description: Adds options on the discution salon
commands:
 setprefix:
  description: "sets prefix for player"
  permission: customchat.plugin.prax
 defprefix:
  description: "sets default prefix for new players"
  permission: customchat.plugin.prax
 delprefix:
  description: "set player's prefix to default"
  permission: customchat.plugin.prax
 setnick:
  description: "sets player's nick"
  permission: customchat.plugin.prax
 delnick:
  description: "returns players's real name"
  permission: customchat.plugin.prax
 mute:
  description: "mute player from chat"
  permission: customchat.plugin.prax
 unmute:
  description: "unmute player from chat"
  permission: customchat.plugin.prax
 disablechat:
  description: "disable chat for all players"
  permission: customchat.plugin.prax
 enablechat:
  description: "enable chat for all player"
  permission: customchat.plugin.prax
permissions:
 customchat.plugin.prax:
  description: "any authorization"
  default: op